# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  full-access-github:
    type: git
    url: https://github.com/
    username: aparakian
    password: ${{secrets.INROS_ACCESS}}
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries:
      - inros-github # Allow version updates for dependencies in this registry
    schedule:
      interval: "daily"
